services:
  postgres:
    container_name: postgres
    image: postgres:16.4
    restart: always
    user: postgres
    secrets:
      - postgres-password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    container_name: server
    # Uncomment the following lines if you want to test local code changes
    # build:
    #   context: .
    #   target: final
    image: ghcr.io/pactmd/ioun:latest
    environment:
      - RUST_LOG=info
    env_file:
      - .env.prod
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy

secrets:
  postgres-password:
    # because of this issue: https://github.com/docker/compose/issues/8305
    # if this file is missing there will be no warning but the container will break if you're using windows
    file: secrets/postgres-password

volumes:
  postgres-data:
